cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
stages:
# At first debian : init variables
- build-debian
- create-debian-package
- test-publish-debian
###
- build
- create-package
- test-publish

include:
  - 'gitlabci/debianbuster.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
